name: Go Global Test

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  test-module:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    
    steps:
    - name: Action init
      uses: actions/checkout@v4


    - name: Cache [ubuntu] init
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache [macos] init
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: go.sum [macos, ubuntu] init
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      run: |
        if [ ! -f "go.sum" ]; then
          echo "File 'go.sum' does not exist. Creating..."
          echo "" > go.sum
        fi
        if [ ! -f "pkg/module/go.sum" ]; then
          echo "File 'pkg/module/go.sum' does not exist. Creating..."
          echo "" > pkg/module/go.sum
        fi

    - name: go.sum [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        if not exist "go.sum" (
          echo "File 'go.sum' does not exist. Creating..."
          echo "" > "go.sum"
        )
        if not exist "pkg\module\go.sum" (
          echo "File 'pkg\module\go.sum' does not exist. Creating..."
          echo "" > "pkg\module\go.sum"
        )


    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
      

    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
