name: Global

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

#**********************************************************************************************************************#
  test-module:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - name: Action init
      uses: actions/checkout@v4

########################################################################################################################

    - name: Cache [ubuntu] init
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          pkg/module/go.sum
          go.sum
        key: ${{ runner.os }}-go-local

    - name: Cache [macos] init
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
          pkg/module/go.sum
          go.sum
        key: ${{ runner.os }}-go-local
        enableCrossOsArchive: true

    - name: Cache [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
          pkg/module/go.sum
          go.sum
        key: ${{ runner.os }}-go-local
        enableCrossOsArchive: true

########################################################################################################################

    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true

    - name: go.sum [macos, ubuntu] init
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      run: |
        if [ ! -f "go.sum" ]; then
          go mod tidy
        fi
        if [ ! -f "pkg/module/go.sum" ]; then
          cd pkg/module/
          go mod tidy
        fi
      working-directory: ${{ github.workspace }}

    - name: go.sum [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        if (-not (Test-Path "go.sum")) {
          go mod tidy
        }
        if (-not (Test-Path "pkg\module\go.sum")) {
          cd pkg\module\
          go mod tidy
        }
      working-directory: ${{ github.workspace }}

########################################################################################################################

    - name: Save Cache
      uses: actions/cache@v4

########################################################################################################################

    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
