name: Go Global Test

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  test-module:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    
    steps:
    - name: Action init
      uses: actions/checkout@v4


     # Инициализация кеша для линукса
    - name: Cache [ubuntu] init
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # Инициализация кеша для мака
    - name: Cache [macos] init
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # Инициализация кеша для винды
    - name: Cache [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


      # Инициализация создаем go.sum для линукса и мака если его нет
    - name: go.sum [macos, ubuntu] init
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      run: |
        if [ ! -f "go.sum" ]; then
          echo "File 'go.sum' does not exist. Creating..."
          echo "\n" > go.sum
        fi
        if [ ! -f "pkg/module/go.sum" ]; then
          echo "File 'pkg/module/go.sum' does not exist. Creating..."
          echo "\n" > pkg/module/go.sum
        fi

      # Инициализация создаем go.sum для винды если его нет
    - name: go.sum [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        if (-not (Test-Path "go.sum")) {
          echo "File 'go.sum' does not exist. Creating..."
          echo "\n" > "go.sum"
        }
        if (-not (Test-Path "pkg\module\go.sum")) {
          echo "File 'pkg\module\go.sum' does not exist. Creating..."
          echo "\n" > "pkg\module\go.sum"
        }


      # Инициализация Go
    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
      
      # Инициализация Запускаем тест для модуля
    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
