name: Go Global Test

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  test-module:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    
    steps:
    - name: Action init
      uses: actions/checkout@v4
    
    - name: Cache init
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-local
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
      

    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
