name: Global Test

on:
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  test-module:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    
    steps:
    - name: Action init
      uses: actions/checkout@v4


     # Инициализация кеша для линукса
    - name: Cache [ubuntu] init
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-local
        restore-keys: |
          ${{ runner.os }}-go-

      # Инициализация кеша для мака
    - name: Cache [macos] init
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-local
        restore-keys: |
          ${{ runner.os }}-go-

      # Инициализация кеша для винды
    - name: Cache [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-local
        restore-keys: |
          ${{ runner.os }}-go-
        

      # Инициализация Go
    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true


      # Инициализация создаем go.sum для линукса и мака если его нет
    - name: go.sum [macos, ubuntu] init
      if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
      run: |
        if [ ! -f "go.sum" ]; then
          go mod tidy
        fi
        if [ ! -f "pkg/module/go.sum" ]; then
          cd pkg/module/
          go mod tidy
        fi
      # Инициализация создаем go.sum для винды если его нет
    - name: go.sum [windows] init
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        if [ ! -f "go.sum" ]; then
          go mod tidy
        fi
        if [ ! -f "pkg/module/go.sum" ]; then
          cd pkg\module\
          go mod tidy
        fi
        
        
      
      # Инициализация Запускаем тест для модуля
    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
