name: Go Test module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Action init
    - uses: actions/checkout@v3
    
    - name: Cache init
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: go.sum init
      run: |
        if [ ! -f "go.sum" ]; then
          echo "File 'go.sum' does not exist. Creating..."
          echo "" > go.sum
        fi
        if [ ! -f "./pkg/module/go.sum" ]; then
          echo "File './pkg/module/go.sum' does not exist. Creating..."
          echo "" > ./pkg/module/go.sum
        fi

    - name: Goland init
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
      

    - name: Start Test
      run: go test -v ./pkg/module -args 'logLVL=panic'
